export type ManagedImageSectionDefinition = {
  id: string;
  group: string;
  label: string;
  defaultPublicId: string;
  defaultAlt: string;
  paths: string[];
  defaultInfo?: string;
  hiddenInAdmin?: boolean;
};

export const MANAGED_IMAGE_SECTIONS: ManagedImageSectionDefinition[] = [
  {
    id: "home.hero.avatar",
    group: "Inicio",
    label: "Avatar principal",
    defaultPublicId: "MarcelaPedrosa_ig7ogm",
    defaultAlt: "Retrato de Marcela Pedrosa",
    paths: ["/"],
  },
  {
    id: "home.hero.banner",
    group: "Inicio",
    label: "Banner principal",
    defaultPublicId: "bosque_wvvs3r",
    defaultAlt: "Obra de Marcela Pedrosa",
    paths: ["/"],
  },
  {
    id: "home.offer.image",
    group: "Inicio",
    label: "Oferta del mes",
    defaultPublicId: "elefante_l0mpmz",
    defaultAlt: "Oferta del mes de Marcela Pedrosa",
    paths: ["/"],
  },
  {
    id: "press.feature.image",
    group: "Prensa",
    label: "Imagen destacada de prensa",
    defaultPublicId: "prensa_zr8m9e",
    defaultAlt: "Recorte de prensa de Marcela Pedrosa",
    paths: ["/prensa"],
  },
  {
    id: "pages.artista-visual.hero",
    group: "Páginas SEO",
    label: "Hero artista visual Biobío",
    defaultPublicId: "gente_ik69lq",
    defaultAlt: "Obra de Marcela Pedrosa, artista visual del Biobío",
    paths: ["/artista-visual-biobio"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.ceramica.hero",
    group: "Páginas SEO",
    label: "Hero cerámica artística",
    defaultPublicId: "elefante_l0mpmz",
    defaultAlt: "Cerámica artística de Marcela Pedrosa en Concepción",
    paths: ["/ceramica-artistica-concepcion"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.impresionismo.hero",
    group: "Páginas SEO",
    label: "Hero impresionismo figurativo",
    defaultPublicId: "bosque_wvvs3r",
    defaultAlt: "Ejemplo de impresionismo figurativo de Marcela Pedrosa",
    paths: ["/impresionismo-figurativo-chile"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.mujeres.hero",
    group: "Páginas SEO",
    label: "Hero mujeres artistas chilenas",
    defaultPublicId: "gente_ik69lq",
    defaultAlt: "Obra de Marcela Pedrosa, mujer artista chilena",
    paths: ["/mujeres-artistas-chilenas"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.oleo.hero",
    group: "Páginas SEO",
    label: "Hero óleo sobre tela",
    defaultPublicId: "mujer_nb6pao",
    defaultAlt: "Pintura al óleo sobre tela de Marcela Pedrosa",
    paths: ["/oleo-sobre-tela-chile"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.pintora.hero",
    group: "Páginas SEO",
    label: "Hero pintora en Concepción",
    defaultPublicId: "bosque_wvvs3r",
    defaultAlt: "Obra de Marcela Pedrosa, pintora en Concepción",
    paths: ["/pintora-concepcion"],
    hiddenInAdmin: true,
  },
  {
    id: "pages.taller.hero",
    group: "Páginas SEO",
    label: "Hero taller de arte",
    defaultPublicId: "elefante_l0mpmz",
    defaultAlt: "Obra creada en el taller de arte de Marcela Pedrosa",
    paths: ["/taller-arte-concepcion"],
    hiddenInAdmin: true,
  },
  {
    id: "gallery.c1",
    group: "Galería",
    label: "Pinturas c1",
    defaultPublicId: "bosque_wvvs3r",
    defaultAlt: "Pintura c1 de Marcela Pedrosa",
    defaultInfo: "158x122 óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c2",
    group: "Galería",
    label: "Pinturas c2",
    defaultPublicId: "gente_ik69lq",
    defaultAlt: "Pintura c2 de Marcela Pedrosa",
    defaultInfo: "110x110 óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c3",
    group: "Galería",
    label: "Pinturas c3",
    defaultPublicId: "elefante_l0mpmz",
    defaultAlt: "Pintura c3 de Marcela Pedrosa",
    defaultInfo: "90x120 óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c4",
    group: "Galería",
    label: "Pinturas c4",
    defaultPublicId: "mujer_nb6pao",
    defaultAlt: "Pintura c4 de Marcela Pedrosa",
    defaultInfo: "100x130 óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c5",
    group: "Galería",
    label: "Pinturas c5",
    defaultPublicId: "c5_t6xso9",
    defaultAlt: "Pintura c5 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c6",
    group: "Galería",
    label: "Pinturas c6",
    defaultPublicId: "c6_ab7jmc",
    defaultAlt: "Pintura c6 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c7",
    group: "Galería",
    label: "Pinturas c7",
    defaultPublicId: "c7_o7ggf4",
    defaultAlt: "Pintura c7 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c8",
    group: "Galería",
    label: "Pinturas c8",
    defaultPublicId: "c8_pw3lea",
    defaultAlt: "Pintura c8 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c9",
    group: "Galería",
    label: "Pinturas c9",
    defaultPublicId: "c9_kf7psh",
    defaultAlt: "Pintura c9 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c10",
    group: "Galería",
    label: "Pinturas c10",
    defaultPublicId: "c10_trroe3",
    defaultAlt: "Pintura c10 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c11",
    group: "Galería",
    label: "Pinturas c11",
    defaultPublicId: "c11_oy6mdw",
    defaultAlt: "Pintura c11 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c12",
    group: "Galería",
    label: "Pinturas c12",
    defaultPublicId: "c12_qtsjik",
    defaultAlt: "Pintura c12 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c13",
    group: "Galería",
    label: "Pinturas c13",
    defaultPublicId: "c13_iqxkyv",
    defaultAlt: "Pintura c13 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c14",
    group: "Galería",
    label: "Pinturas c14",
    defaultPublicId: "c14_v0dphn",
    defaultAlt: "Pintura c14 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gallery.c15",
    group: "Galería",
    label: "Pinturas c15",
    defaultPublicId: "c15_rntbzb",
    defaultAlt: "Pintura c15 de Marcela Pedrosa",
    defaultInfo: "óleo sobre tela",
    paths: ["/pinturas"],
  },
  {
    id: "gres.c1",
    group: "Cerámica gres",
    label: "Cerámica gres c1",
    defaultPublicId: "bosque_wvvs3r",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c2",
    group: "Cerámica gres",
    label: "Cerámica gres c2",
    defaultPublicId: "gente_ik69lq",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c3",
    group: "Cerámica gres",
    label: "Cerámica gres c3",
    defaultPublicId: "elefante_l0mpmz",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c4",
    group: "Cerámica gres",
    label: "Cerámica gres c4",
    defaultPublicId: "mujer_nb6pao",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c5",
    group: "Cerámica gres",
    label: "Cerámica gres c5",
    defaultPublicId: "c5_t6xso9",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c6",
    group: "Cerámica gres",
    label: "Cerámica gres c6",
    defaultPublicId: "c6_ab7jmc",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c7",
    group: "Cerámica gres",
    label: "Cerámica gres c7",
    defaultPublicId: "c7_o7ggf4",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c8",
    group: "Cerámica gres",
    label: "Cerámica gres c8",
    defaultPublicId: "c8_pw3lea",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c9",
    group: "Cerámica gres",
    label: "Cerámica gres c9",
    defaultPublicId: "c9_kf7psh",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c10",
    group: "Cerámica gres",
    label: "Cerámica gres c10",
    defaultPublicId: "c10_trroe3",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c11",
    group: "Cerámica gres",
    label: "Cerámica gres c11",
    defaultPublicId: "c11_oy6mdw",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
  {
    id: "gres.c12",
    group: "Cerámica gres",
    label: "Cerámica gres c12",
    defaultPublicId: "c12_qtsjik",
    defaultAlt: "Cerámica en gres de Marcela Pedrosa",
    defaultInfo: "cerámica gres",
    paths: ["/esculturas"],
  },
];

export function getManagedImageSectionDefinition(id: string) {
  return MANAGED_IMAGE_SECTIONS.find((section) => section.id === id);
}
