import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 👇 importa *named* desde app/components (ajusta el path si lo movés)
import { LanguageProvider, LanguageToggle } from "./components/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Provider CLIENTE envolviendo todo el contenido */}
        <LanguageProvider>
          {/*<div className="mx-auto max-w-6xl px-4 sm:px-6 pt-4">
            <div className="flex justify-end">
              <LanguageToggle />
            </div>
          </div>

          {/* 👇 Asegurate de que children esté DENTRO del Provider */}
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}